### ISSUE TITLE
composer - no matching packages

### ISSUE THREAD

**Issue by safrazik** [adrotec/breeze.server.php.demo#1]
_From @slawojstanislawski on August 8, 2015 7:55_

Upon executing composer update, the following error shows up:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for symfony/validator dev-master -> satisfiable by symfony/validator[dev-master].
    - symfony/validator dev-master requires symfony/translation ~2.8|~3.0 -> no matching package found.
  Problem 2
    - Installation request for adrotec/breeze.server.php dev-master -> satisfiable by adrotec/breeze.server.php[dev-master].
    - adrotec/breeze.server.php dev-master requires jms/serializer ~1.0 -> no matching package found.

Perhaps your package should depend on stable releases instead of dev-master? I changed "dev-master" to "@dev" and it temporarily fixes the problem, for the lack of any better/quicker solution, if that can be called so.

It's acutally an issue with the demo: https://github.com/adrotec/breeze.server.php.demo

_Copied from original issue: adrotec/breeze.server.php#20_

**Comment by safrazik** [comment]
the library itself doesn't depend on any development packages. But the demo requires dev of this library for testing. It is not an issue of the library but the demo.

**Comment by awelles** [comment]
Worked for me with the demo's composer.json as such:
( made a pull request )

{
    "name": "vendor/breeze-server-demo",
    "description": "Description of project BreezeServerDemo.",
    "authors": [
        {
            "name": "mrsafraz",
            "email": "mr.safraz@gmail.com"
        }
    ],
    "require": {
        "jms/serializer": "^1.0.0",
        "doctrine/orm": "v2.4.2",
        "symfony/config": "2.5._",
        "symfony/validator": "^2.7",
        "symfony/http-foundation": "2.5._",
        "symfony/http-kernel": "2.5._",
        "symfony/debug": "2.5._",
        "adrotec/breeze.server.php": "dev-master",
        "ext-sqlite3": "_",
        "ext-pdo_sqlite": "_"

```
},
"autoload": {
    "psr-0": {"": "src/"}
}
```

}

**Comment by safrazik** [comment]
@awelles  Thanks for the pull request. It has been merged.
